version: "3" # composeファイルのバージョン
services:
  md2s: # サービス名
    container_name: md2s
    build:
      context: . # ビルドするコンテキストのパス
      dockerfile: ./build/go/Dockerfile # ビルドに使うDockerファイルのパス
    volumes: # マウントディレクトリ
      - ./src:/go/src/app
    hostname: localhost
    ports:
      - 8080:8080 #　デバッグ用のポート
      # 本番環境用のポート
      - ${process.env.PORT}:${process.env.PORT}
    tty: true # コンテナの永続化
    env_file: # .envファイル
      - .env
    networks:
      - private-net

  # posttgresql
  posttgresql-db:
    container_name: ${DB_HOST}
    image: postgres:14
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./build/postgresql/data:/var/lib/postgresql/data
      - ./build/postgresql/init:/docker-entrypoint-initdb.d # DBを初期化
    ports:
      - ${DB_PORT}:${DB_PORT}
    networks:
      - private-net

volumes:
  db-store:
    driver: local
networks:
  private-net:
    driver: bridge
